### ISSUE TITLE
[Meta] Issues regarding master branch

### ISSUE THREAD

**Issue by nijikokun** [currency-cop/currency-cop#34]
Issues based on the master branch will be ignored, as I am working on a new form of Currency Cop under [feat/remove-material-ui](https://github.com/currency-cop/currency-cop/tree/feat/remove-material-ui)

It is a huge undertaking which moves away from the old model of overly-aggressive fetching of resources, and using a horrible UI framework, (see changelog below).

**Download the Latest Release**

https://github.com/currency-cop/currency-cop/releases

**or Compile from source**

1. Clone the repository
1. clone this branch
1. `npm install`
1. `npm run prod`

**Changelog**

- Moving away from `willComponentMount` in favor of `constructor` based system
- Removed Material UI Framework
- Moved components out of single file.
- Implemented request caching system
- Implemented throttled request system
- Implemented asynchronous report updating
- Refactored portfolio/report aggregations to be more space/memory efficient
- Added support for Unique Items
- Added support for Gems with Gem Quality Support
- Added support for 6L items
- Added support for Variant Items
- Implemented portfolio belongs to a dead league, functionality
- Fixed last updated time not being refreshed
- Fixed relic prices being applied to non-relic items
- Fixed six-link prices being applied to non-6l items
- Fixed ancient prices being applied to non-ancient items
- Fixed low-confidence prices being used
- Began adding support for swapping currency
- Proper windows icons for applications in app bar
- Improved logo

**Changes Since Writing Issue**
- Added active state to portfolios in sidebar
- Fixed Gain / Loss using `-` for 0 change
- Added new app bar to the loading / login screens
- Added history dropdown
- Improved form styles
- Fixed blank screen before login
- Fixes confidence filters
- Use github releases for version check
- Implements dashboard messages (placeholder stuff, i guess)
- Limits history dropdown to 5 items
- Updates portfolio on save
- Use price icon for items
- Update form style
- Add support for maps
- Fix poe.ninja api hostname
- Add support for events

**Todo**

- [x] Update portfolio on save
- [x] Fix item icon
- [x] Version check
- [x] Update Portfolio Screen
- [x] Figure out how to prevent rendering a section of the app bar unusable while scrolling the table on a portfolio (weird)
- [x] Add support for maps
- [x] Fix poe.ninja api hostname
- [x] Add support for events
- [x] Implement sorting
- [x] Fix old maps in standard (need help)
- [x] Delete Portfolio
- [x] Fix logout button
- [ ] Header Chart
- [ ] Implement search

**Comment by Smeagol001** [comment]
soo how to get the new version then?

**Comment by nijikokun** [comment]
@smeagol001 check the "if you want to beta test" section of the post

**Comment by Smeagol001** [comment]
how to do that with windows? im kind of a noob  in regards to github^^

**Comment by romdi** [comment]
@Smeagol001 You have to install git and nodejs. Clone the project via git, open cmd in the project folder and run the commands above.

**Comment by O4epegb** [comment]
Commands are kinda wrong, though)

>Clone the repository
>npm run install
>npm start

There is no such commands in `package.json`, you should probably run just `npm install` and then `npm run dev`. But I have troubles after that

`
Uncaught error: AccountActions.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object. - Invariant Violation: AccountActions.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
`

More errors after that

**Comment by nijikokun** [comment]
Must be on the right branch

**Comment by O4epegb** [comment]
I am on the right branch :) `feat/remove-material-ui`. You can double check, but there is no such commands as `npm run install` and `npm start`

**Comment by nijikokun** [comment]
Yeah, but you shouldn't get any errors, just in-case, I've made a release https://github.com/currency-cop/currency-cop/releases/tag/2.0.0

**Comment by nijikokun** [comment]
So I found a few issues, which have been resolved, so anyone who does the install / run prod won't have any issues now.

**Comment by nijikokun** [comment]
@O4epegb apologies, I haven't ever logged out, just saw the error you were running into. I thought you were encountering this on the build phase.

Pushing out an update:

https://github.com/currency-cop/currency-cop/releases/tag/2.0.0-beta.2

**Comment by O4epegb** [comment]
Yep, it works now!

But now I have errors after generating porfolio and trying to select it :)

`[11:52:15] [CRITICAL] [Core] Uncaught error: Cannot read property 'items' of null - TypeError: Cannot read property 'items' of null
    at AppPortfolio.render (http://localhost:8080/bundle.js:59270:53)
    at http://localhost:8080/bundle.js:36722:21
    at measureLifeCyclePerf (http://localhost:8080/bundle.js:36002:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8080/bundle.js:36721:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:8080/bundle.js:36748:32)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8080/bundle.js:36288:30)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8080/bundle.js:36184:21)
    at Object.mountComponent (http://localhost:8080/bundle.js:6772:35)
    at Object.updateChildren (http://localhost:8080/bundle.js:35855:51)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:8080/bundle.js:40637:32)`

EDIT: But after app reload it is now fine, I was able to select portfolio, so you need to check why it might crash right after generating first portfolio maybe

**Comment by nijikokun** [comment]
@O4epegb Resolved in 2.0.0-beta.3

**Comment by nijikokun** [comment]
New release button definitely works 😀 

![image](https://user-images.githubusercontent.com/198276/39228135-40f9d32c-4811-11e8-8331-6a8bbbc1b3b0.png)

**Comment by ghayes7** [comment]
"Houston we have a problem" when starting CC while logged in (logging out and in results in the same thing). Any log files I can peek at for a more helpful error?

**Comment by nijikokun** [comment]
Check under `%appdata%/currency-cop`

**Comment by nijikokun** [comment]
[`2.0.0-beta.5`](https://github.com/currency-cop/currency-cop/releases/tag/2.0.0-beta.5) released 🎉

**Comment by chinhodado** [comment]
I tested the latest beta and it's really buggy. I created one portfolio for Bestiary and Standard and they worked, but then I created one for Flashback and but somehow it became Bestiary as well and I had 2 Bestiary portfolio. I couldn't delete one of them so I tried to change the league and everything seemed to break, items on different league got merged together. Sometimes opening the app would get it stuck on Gathering prices and tabs.

**Comment by nijikokun** [comment]
Thank you for testing and the feedback!

If it gets stuck on the prices & tabs  that means its still fetching, the poe api takes a while sometimes.

Will look into your first issue

**Comment by nijikokun** [comment]
@chinhodado in the next release there will be text next to the Gather prices and tabs indicating which one it is fetching. Maybe this will give you a feeling of advancement :)

**Comment by nijikokun** [comment]
[`2.0.0-beta.7`](https://github.com/currency-cop/currency-cop/releases/tag/2.0.0-beta.7) released 🎉 

- Sorting
- Individual Price
- Better Messaging
- 5L / 6L reporting works
- ...and more!

**Comment by chinhodado** [comment]
Can you make fetching prices running in the background when first opening the app? Right now on start up it's fetching currency and item prices for 6 leagues for like 30 seconds when most people are only interested in a league or two, not to mention some don't care about items and only care about pure currency, etc. It makes more sense to show the portfolio right away, then update the portfolio's worth as prices are coming back.

**Comment by nijikokun** [comment]
@chinhodado Fetching starts immediately to ensure that leagues are setup prior to entering the application to ensure that the creation screen is fully functional, do you stop and start the application frequently? This could cause your account to be rate limited as there is no control mechanism for this type of action.

**Comment by chinhodado** [comment]
The portfolio creation is only dependent on the list of league and list of tabs for each league right? All other info are not needed to create a portfolio, only to update its worth. This also ensure that you don't have to fetch prices for leagues that you don't care about. So in short

 - When the app is first started, fetch prices only for leagues that have at least one portfolio created. If no portfolio is created, don't fetch anything. Fetch in the background and possibly display a progress bar  but don't block the UI.

 - After a portfolio is created, add the portfolio's league to the list of league to fetch price for

**Comment by nijikokun** [comment]
[`2.0.0-beta.8`](https://github.com/currency-cop/currency-cop/releases/tag/v2.0.0-beta.8) released 🎉

- Added delete button 🎉 
- Datafile writes are now debounced, improves i/o usage.
- Fixes price issue with Tabula Rasa, and other items that have `links = 0`.
- Fixed issue where price changes had no colors
- Fixed sorting by price in portfolio view
- Fixed issue where users could not view, edit, or modify syncing tabs
- Fixed issue with old league tabs not being able to update settings due to missing tabs
- Fixed issue where item images no longer report relic status, relics are now properly matched
